class GuiLabel:

    NO_ALERT = "Nessun errore riscontrato"
    ALERT_THE_SKY_LOST = "Connessione con the Sky persa"
    ALERT_THE_SKY_ERROR = "Errore di TheSky"
    ALERT_CHECK_CURTAINS_SWITCH = "Controllare switch tende - ricalibrazione"
    ALERT_CRAC_ANOMALY = "Anomalia CRaC: stato invalido dei componenti"
    ALERT_TELESCOPE_ROOF = "Attenzione, Telescopio vicino al tetto"
    ALERT_TELESCOPE_ROOF_CLOSING = "Attenzione, Telescopio non in park e tetto in chiusura"
    ALERT_TELESCOPE_OPERATIVE = "Attenzione telescopio operativo: {status}"
    ALERT_CURTAINS_ENABLED = "Attenzione tende aperte"
    ALERT_ROOF_CLOSED = "Attenzione tetto chiuso"
    CURTAINS_DISABLED = "Disattivata"
    CURTAINS_CLOSED = "Chiusa"
    CURTAINS_STOPPED = "Ferma"
    CURTAINS_OPEN = "Aperta"
    CURTAINS_ANOMALY = "Anomalia"
    TELESCOPE_PARKED = "Parked"
    TELESCOPE_FLATTER = "Flatter"
    TELESCOPE_SECURED = "In Sicurezza"
    TELESCOPE_SYNC_OFF = "No Sync"
    TELESCOPE_SYNC_ON = "Sync On"
    TELESCOPE_NE = "NordEst"
    TELESCOPE_EE = "Est"
    TELESCOPE_SE = "SudEst"
    TELESCOPE_SW = "SudOvest"
    TELESCOPE_WW = "Ovest"
    TELESCOPE_NW = "NordOvest"
    TELESCOPE_ANOMALY = "Anomalia"
    TELESCOPE_ERROR = "Errore"
    TELESCOPE_TRACKING_ON = "Track On"
    TELESCOPE_TRACKING_OFF = "Track Off"
    TELESCOPE_SLEWING_ON = "Slewing On"
    TELESCOPE_SLEWING_OFF = "Slewing Off"
    ROOF_CLOSED = "Chiuso"
    ROOF_OPEN = "Aperto"
    ON = "On"
    OFF = "Off"
    STAND_BY = "Standby"


class GuiKey:

    OPEN_ROOF = "R"
    SYNC_TELE = "S"
    PARK_TELE = "P"
    FLAT_TELE = "F"
    CLOSE_ROOF = "T"
    ENABLED_CURTAINS = "1"
    DISABLED_CURTAINS = "0"
    CALIBRATE_CURTAINS = "2"
    SHUTDOWN = "-"
    CONTINUE = "c"
    EXIT = "E"
    TIMEOUT = "__TIMEOUT__"
    PANEL_ON = "L"
    PANEL_OFF = "D"
    LIGHT_ON = "K"
    LIGHT_OFF = "J"
    POWER_ON_TELE = "W"
    POWER_OFF_TELE = "X"
    POWER_ON_CCD = "A"
    POWER_OFF_CCD = "O"
